#!/usr/bin/env python3
"""
Telegram推送 - Elon Musk推文数据更新
"""

import json
import requests
from datetime import datetime

def load_config():
    """加载Telegram配置"""
    try:
        with open('telegram_config.json', 'r') as f:
            return json.load(f)
    except:
        return None

def send_telegram_message(message):
    """发送Telegram消息"""

    config = load_config()

    if not config or not config.get('enabled'):
        print("⚠️  Telegram未配置或未启用")
        return False

    bot_token = config.get('bot_token')
    chat_id = config.get('chat_id')

    if bot_token == "YOUR_BOT_TOKEN_HERE" or chat_id == "YOUR_CHAT_ID_HERE":
        print("⚠️  请先配置Telegram Bot Token和Chat ID")
        return False

    try:
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"

        data = {
            'chat_id': chat_id,
            'text': message,
            'parse_mode': 'Markdown'
        }

        response = requests.post(url, json=data, timeout=10)

        if response.status_code == 200:
            print("✅ Telegram推送成功")
            return True
        else:
            print(f"❌ Telegram推送失败: {response.text}")
            return False

    except Exception as e:
        print(f"❌ Telegram推送错误: {e}")
        return False


def send_update_notification(today_count, recent_data, stats):
    """发送更新通知"""

    now = datetime.now()
    today_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    # 计算趋势
    recent_3_avg = sum(r['count'] for r in recent_data[-3:]) / 3
    previous_3_avg = sum(r['count'] for r in recent_data[-6:-3]) / 3 if len(recent_data) >= 6 else recent_3_avg

    if recent_3_avg > previous_3_avg * 1.1:
        trend = "📈 上升"
    elif recent_3_avg < previous_3_avg * 0.9:
        trend = "📉 下降"
    else:
        trend = "➡️ 稳定"

    # 构建消息
    message = f"""🤖 *Elon Musk 推文数据更新*

📅 *{today_str}* | 🕐 *{time_str}*

━━━━━━━━━━━━━━━━━━━━━
📊 *今日数据*
   今天: *{today_count}* 条
   7天平均: {stats['7day_avg']:.1f} 条/天

━━━━━━━━━━━━━━━━━━━━━
📈 *最近3天*
"""

    for day in recent_data[-3:]:
        message += f"   {day['date']}: {day['count']} 条\n"

    message += f"""
━━━━━━━━━━━━━━━━━━━━━
📉 *趋势*: {trend}

📊 *历史统计*
   总天数: {stats['total_days']} 天
   平均: {stats['avg']:.1f} 条/天
   最高: {stats['max']} 条

📂 Excel已更新
━━━━━━━━━━━━━━━━━━━━━
🤖 Generated by polymarket-predictor
"""

    return message


def main():
    """主函数 - 发送通知"""

    # 读取最新数据
    with open('data/daily_tweets.json', 'r') as f:
        data = json.load(f)

    # 获取今天的数量
    today_str = datetime.now().strftime("%Y-%m-%d")
    today_count = 0
    for record in data:
        if record['date'] == today_str:
            today_count = record['count']
            break

    # 最近数据
    recent_data = sorted(data, key=lambda x: x['date'])[-7:]

    # 统计
    counts = [r['count'] for r in data]
    stats = {
        'total_days': len(data),
        'avg': sum(counts) / len(counts),
        'max': max(counts),
        '7day_avg': sum([r['count'] for r in recent_data]) / len(recent_data)
    }

    # 发送消息
    message = send_update_notification(today_count, recent_data, stats)
    send_telegram_message(message)


if __name__ == "__main__":
    main()
